language: php

php:
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --dev --no-interaction
  - composer require codeclimate/php-test-reporter --dev
  - composer require satooshi/php-coveralls --dev

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/test-reporter
  - php vendor/bin/coveralls

notifications:
  slack: highday:9qVTVUwXr2PER5tUsvkN2X7A
  webhooks:
    urls:
      - https://forge.laravel.com/servers/106521/sites/254209/deploy/http?token=c1J7hUvY1iuJiEUlih3GWmPzfyc2PqIEDoQHBMav
    on_success: always
    on_failure: never

addons:
  code_climate:
    repo_token: 433ff6d8ade5895b6d9c9dd52f3b4f8dc4b6bca4984f60e41b58910e7895966b
