language: php

php:
  - 7.0

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist --optimize-autoloader

script:
  - ls -al
  - ls -al ./*
  - pwd
  - vendor/bin/phpunit

notifications:
  slack: highday:9qVTVUwXr2PER5tUsvkN2X7A
